### PR TITLE
Synchronization

### PR DESCRIPTION
**Pull request by LoLei**
Move synchronization code to own class, set new startup activity with does synchronization and setup list, and starts after it the ListActivity

### CODE REVIEW

**Comment by LoLei** [comment]
Related to #14 and #15?

**Comment by d4bandel** [comment]
they are fixed with this PR

**Comment by codecreativity** [comment]
THIS WILL BE RESOLVED IN #28

**Comment by codecreativity** [comment]
Because in #28 there are no maps anymore, the volley queue seems to be executed in the right order

**Comment by codecreativity** [comment]
or maybe not

**Comment by LoLei** [comment]
This PR is 73 commits behind dev as of #31... Should we just close this and fix this elsewhere?

**Comment by codecreativity** [comment]
remove this, fix it using new code structure?

**Comment by codecreativity** [comment]
Der Lurch, der lurch treibt sein unwesen:
https://de.wikipedia.org/wiki/Hausstaub#.E2.80.9ELurch.E2.80.9C

**Comment by LoLei** [comment]
@danielgpoint is the owner of this branch, let's hear him out.

**Pull request closed without merging**
